### PR TITLE
Minor Changes to project.xml

### PR DESCRIPTION
**Pull request by ElastedAlorian**

### CODE REVIEW

**Review by Mackery6969 — CHANGES_REQUESTED** [review]
if you do that you have to change the build.yml and stuff

**Review by Mackery6969 — CHANGES_REQUESTED** [review]
change Build.yml

**Review by Mackery6969 — COMMENTED** [review]
why brandon file path?

**Comment by SIG7Pro** [comment]
> change Build.yml

I updated Build.yml and added another build script (for debug builds) so yea :)

**Comment by Mackery6969** [comment]
remove brandon

**Review by Mackery6969 — APPROVED** [review]

**Pull request merged**
